name: Destroy AWS
on:
  workflow_dispatch:
    inputs:
      confirm:
        description: "Tem certeza que deseja destruir a infraestrutura? Digite: sim"
        required: true
        default: "não"

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: us-east-1

jobs:
  terraform:
    if: github.event.inputs.confirm == 'sim'
    runs-on: ubuntu-latest
    name: Terraform Destroy
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: true

      - name: Destroy All Modules
        run: |
          for dir in cognito eks acm vpc; do
            echo "Destruindo módulo: $dir"
            cd $dir
            terraform init -backend-config=prd/backend.tfvars
            terraform destroy --var-file=prd/terraform.tfvars --auto-approve
            cd ..
          done
